### ISSUE TITLE
JAVA

### ISSUE THREAD

**Issue by diazgus411** [diazgus411/prework-studyguide#3]
# JAVA

## USER STORY
As a boot camp student
I want the prework notes to be structured on a webpage
So that I can easily find and read the information

## ACCEPTANCE CRITERIA
GIVEN a Prework Study Guide website
WHEN I view the study guide
THEN I can see the four topics I learned listed along with a suggestion on what I should study first

**Comment by PenhaKristalPWT** [comment]
It seems like you have provided a user story and acceptance criteria related to organizing prework notes for a boot camp student. The user story specifies that the student wants the notes to be structured on a webpage to make it easier to find and read the information. The acceptance criteria state that the Prework Study Guide website should include four topics learned, and should suggest a recommended order to study the information. This would enable the student to easily navigate the content and prioritize their study efforts based on the suggested order.

**Comment by BrandenHantz9B** [comment]
User Story:
As a boot camp student
I want the prework notes to be structured on a webpage
So that I can easily find and read the information

Acceptance Criteria:
Given a Prework Study Guide website
When I view the study guide
Then I can see the four topics I learned listed along with a suggestion on what I should study first

Scenario 1: View Prework Study Guide
Given I am a boot camp student
When I visit the Prework Study Guide website
Then I should see a page with the title "Prework Study Guide"
And I should see the following four topics listed in order:
  - Programming Fundamentals
  - Web Development Fundamentals
  - Databases and SQL
  - Git and Version Control
And I should see a suggestion to start with "Programming Fundamentals"

Scenario 2: Click on a Topic
Given I am viewing the Prework Study Guide
When I click on a topic
Then I should be taken to a page with detailed notes on that topic

Scenario 3: Click on "Start Here"
Given I am viewing the Prework Study Guide
When I click on "Start Here"
Then I should be taken to a page with detailed notes on "Programming Fundamentals"


Note that these acceptance criteria are just a suggestion and may need to be adapted to your specific needs.
